<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { UploadResponse } from '@/types/upload'
import JsonPreview from '@/components/JsonPreview.vue'
import XmlPreview from '@/components/XmlPreview.vue'

const previewJson = ref<string>('')
const previewXml = ref<string>('')
const error = ref<string | null>(null)

onMounted(() => {
  const stored = sessionStorage.getItem('latestUpload')
  if (!stored) {
    error.value = 'Upload a document first to see a preview.'
    return
  }

  try {
    const payload = JSON.parse(stored) as UploadResponse
    previewJson.value = JSON.stringify(payload.previewJson, null, 2)
    previewXml.value = payload.previewXml
  } catch (err) {
    error.value = 'Unable to read preview. Please upload again.'
  }
})
</script>

<template>
  <section class="preview-page">
    <header>
      <p class="eyebrow">Step 2</p>
      <h1>Document Preview</h1>
      <p class="lead">Inspect both the JSON and XML renderings generated by the backend.</p>
    </header>

    <p v-if="error" class="error">{{ error }}</p>
    <div v-else class="previews">
      <JsonPreview title="JSON Preview" :content="previewJson" description="Auto-generated structure" />
      <XmlPreview title="XML Preview" :content="previewXml" description="Backend XML representation" />
    </div>
  </section>
</template>

<style scoped>
.preview-page {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  max-width: 1080px;
}

.eyebrow {
  margin: 0;
  text-transform: uppercase;
  letter-spacing: 0.3em;
  font-size: 0.75rem;
  color: #475569;
}

.lead {
  margin: 0.35rem 0 0;
  color: #475569;
}

.previews {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1rem;
}

.error {
  color: #b91c1c;
}
</style>
